sudo: required
services:
  - docker

before_install:
  - docker build -t milanunion/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run milanunion/react-test npm run test

after_success:
  - docker build -t milanunion/multi-client ./client
  - docker build -t milanunion/multi-nginx ./nginx
  - docker build -t milanunion/multi-server ./server
  - docker build -t milanunion/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push milanunion/multi-client
  - docker push milanunion/multi-nginx
  - docker push milanunion/multi-server
  - docker push milanunion/multi-worker


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-686373085295"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"